### Ammo types
Prohibited:
  # Prohibited ammo will never be used by any faction
  - Tandem-Charge
  - AlamoMissile Ammo
Overrides:
  # Overrides will replace final generated values in the configurator.
  # To prohibit a specific munition type for IS or Clans only, set its final weight override to below the value of
  # "mtMunitionWeightThreshold" (see Defaults.Factors.mtMunitionWeightThreshold)
  Munitions:
    Dead-Fire:
      IS: 4.0
  Bombs:
  Factors:

Defaults:
  # Default starting values
  Munitions:
    # Default weights of all munitions; increase or decrease to change relative weights prior to
    # unit- and map-related autoconfiguration.
    Weight: &DefaultWeight 1.0
    LRM:
      Dead-Fire:
        IS: 2.0
        Clan: *DefaultWeight
      Standard:
        IS: 2.0
        Clan: 2.0
      Swarm-I:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Swarm:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Heat-Seeking:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Semi-guided:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Artemis-capable:
        # Never weight Artemis munitions above 0; they are assigned to Artemis-compatible launchers automatically
        IS: &NegativeWeight -1.0
        Clan: *NegativeWeight
      Narc-capable:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Follow The Leader:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Fragmentation:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Thunder:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Thunder-Active:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Thunder-Augmented:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Thunder-Vibrabomb:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Thunder-Inferno:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Anti-TSM:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Listen-Kill:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Smoke:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Mine Clearance:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Anti-Radiation:
        IS: *DefaultWeight
        Clan: *DefaultWeight

    SRM:
      Dead-Fire:
        IS: 2.0
        Clan: *DefaultWeight
      Standard:
        IS: 2.0
        Clan: 2.0
      Tandem-Charge:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Inferno:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Heat-Seeking:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Artemis-capable:
        # Never weight Artemis munitions above 0; they are assigned to Artemis-compatible launchers automatically
        IS: *NegativeWeight
        Clan: *NegativeWeight
      Narc-capable:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Fragmentation:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Acid:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Anti-TSM:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Listen-Kill:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Mine Clearance:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Smoke:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Anti-Radiation:
        IS: *DefaultWeight
        Clan: *DefaultWeight

    AC:
      Precision:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Standard:
        IS: 2.0
        Clan: 2.0
      Armor-Piercing:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Caseless:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Flak:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Tracer:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Flechette:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Armor-Piercing Playtest:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Precision Playtest:
        IS: *DefaultWeight
        Clan: *DefaultWeight

    Arrow:
      Fuel-Air:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Standard:
        IS: 2.0
        Clan: 2.0
      ADA:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Cluster:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Inferno-IV:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Homing:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Thunder:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Thunder Vibrabomb-IV:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Illumination:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Smoke:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Laser Inhibiting:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Davy Crockett-M:
        IS: *DefaultWeight
        Clan: *DefaultWeight

    Artillery:
      Fuel-Air:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Standard:
        IS: 2.0
        Clan: 2.0
      Cluster:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Copperhead:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      FASCAM:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Flechette:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Illumination:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Smoke:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Davy Crockett-M:
        IS: *DefaultWeight
        Clan: *DefaultWeight

    Artillery Cannon:
      Fuel-Air:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Standard:
        IS: 2.0
        Clan: 2.0

    ATM:
      Standard:
        Clan: 1.0
      ER:
        Clan: 2.0
      HE:
        Clan: 2.0

    iATM:
      Standard:
        Clan: 1.0
      ER:
        Clan: 2.0
      HE:
        Clan: 2.0

    Mek Mortar:
      Standard:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Semi-Guided:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Anti-personnel:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Airburst:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Flare:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Smoke:
        IS: *DefaultWeight
        Clan: *DefaultWeight

    Narc:
      Narc Explosive:
        IS: *DefaultWeight
        Clan: *DefaultWeight
      Standard:
        IS: *DefaultWeight
        Clan: *DefaultWeight

  Bombs:
    # These values control the loadout spread, types, and percentages of various bomb roles and munition types
    MapGroundSpreadNormal: 6
    MapGroundSpreadAnti-Mek: 3
    MapGroundSpreadAnti-conventional: 2
    MapGroundSpreadStandoff: 1
    MapGroundSpreadStrike: 2
    MapPirateGroundSpreadNormal: 7
    MapPirateGroundSpreadFirestorm: 3
    normalBombLoad_HE: 40
    normalBombLoad_LG: 5
    normalBombLoad_CLUSTER: 30
    normalBombLoad_INFERNO: 15
    normalBombLoad_THUNDER: 10
    antiMekBombLoad_HE: 55
    antiMekBombLoad_LG: 15
    antiMekBombLoad_INFERNO: 10
    antiMekBombLoad_THUNDER: 10
    antiMekBombLoad_HOMING: 10
    antiConvBombLoad_CLUSTER: 50
    antiConvBombLoad_INFERNO: 40
    antiConvBombLoad_FAE_SMALL: 8
    standoffBombLoad_ARROW: 40
    standoffBombLoad_HOMING: 60
    strikeBombLoad_LG: 45
    strikeBombLoad_HOMING: 25
    strikeBombLoad_HE: 30
    lowTechBombLoad_HE: 35
    lowTechBombLoad_RL: 65
    pirateBombLoad_HE: 7
    pirateBombLoad_RL: 45
    pirateBombLoad_INFERNO: 35
    pirateBombLoad_CLUSTER: 5
    pirateBombLoad_FAE_SMALL: 6
    pirateBombLoad_FAE_LARGE: 2
    pirateFirestormBombLoad_INFERNO: 60
    pirateFirestormBombLoad_FAE_SMALL: 30
    pirateFirestormBombLoad_FAE_LARGE: 10
    antiAirBombLoad_RL: 40
    antiAirBombLoad_LAA: 40
    antiAirBombLoad_AAA: 15
    antiAirBombLoad_AS: 4
    antiAirBombLoad_ASEW: 1
    antiShipBombLoad_AAA: 50
    antiShipBombLoad_AS: 35
    antiShipBombLoad_ASEW: 15
    pirateAntiBombLoad_RL: 60
    pirateAntiBombLoad_LAA: 30
    pirateAntiBombLoad_AAA: 10
    # Sets the minimum + (0 ~ N) range of bomber units to equip.
    percentBombersToEquipMin: 40
    percentBombersToEquipRange: 60
    # For each Aerospace unit, if 1d6 is equal or below threshold, equip for CAP
    fightersLoadForCAPRollTargetThreshold: 1
    bomberMinUnarmedSafeThrustValue: 2
    bomberMinArmedSafeThrustValue: 3
    fighterCAPMinUnarmedSafeThrustValue: 2
    fighterCAPMinArmedSafeThrustFractionDivisor: 2.0
    maxBomberLoadFactorDivisor: 5.0
    maxBomberLoadThrustDiffFactor: 5
    maxPercentBomberLoadToEquipMin: 50
    maxPercentBomberLoadToEquipRange: 40
    bombersToAddTagMaxCount: 3
    bomberRandomThresholdMaxPercent: 100
    fighterCAPRandomPercentageRange: 100
    fighterCAPAntiShipLoadOutRandomPercentageMax: 20
    # If a munition must be replaced, range and threshold of RL vs HE
    ReplacementIntRange: 2
    ReplacementRLThreshold: 0
    maxBombApplicationLoopCount: 10
    maxBombOrdnanceWeightPercentThreshold: 100
    RandomReplaceRating4PlusThreshold: 5
    RandomReplaceRating3PlusThreshold: 10
    RandomReplaceRating2PlusThreshold: 25
    RandomReplaceRating1PlusThreshold: 40
    RandomReplaceRating0PlusThreshold: 80
  Factors:
    # These values adjust how munition categories are valued by various triggers and are used by the MunitionTree class
    #
    # Decrease count-reducing ammo wight factor if own team: enemy team count < this factor
    mtReducingAmmoReduceIfUnderFactor: 2.0
    # Increase count-reducing ammo weight factor if own team: enemy team count >= this factor
    mtReducingAmmoIncreaseIfOverFactor: 3.0
    # Min number of bombers to cause Flak munition weight increase (default is 1 or more)
    mtFlakMinBombersExceedThreshold: 0.0
    # If enemy force is 1/<this value> fliers of any kind, weight Flak munitions higher
    mtFlakEnemyFliersFractionDivisor: 4.0
    # If enemy force is 1/<this value> fast movers, weight precision-increasing munitions higher
    mtPrecisionAmmoFastEnemyFractionDivisor: 4.0
    # If number of enemy units with advanced armor types exceeds this, weight high-powered munitions (TC, AP) higher
    mtHPAmmoAdvArmorEnemiesExceedThreshold: 0.0
    # If enemy force is 1/<this value> fireproof units, reduce heat- and fire-based munition weight
    mtFireproofMaxEnemyFractionDivisor: 4.0
    # If enemy force is 1/<this value> infantry units, increase anti-infantry munition weight
    mtInfantryEnemyExceedsFractionDivisor: 4.0
    # If enemy force is 1/<this value> vehicles, increase heat- and fire-producing munition weight
    mtVeeEnemyExceedsFractionDivisor: 4.0
    # If enemy force is 1/<this value> BA units, increase AE, AP, TC, and heat/fire munitions (mod fireproof)
    mtBAEnemyExceedsFractionDivisor: 4.0
    # If enemy force contains more than this number of ECM units, weight seeking munitions up and guided down
    mtSeekingAmmoEnemyECMExceedThreshold: 1.0
    # If friendly forces' TAG count exceeds this threshold, weight guided munitions higher
    mtGuidedAmmoFriendlyTAGThreshold: 1.0
    # If friendly forces' NARC count exceeds this threshold, weight guided munitions higher
    mtGuidedAmmoFriendlyNARCThreshold: 1.0
    # If friendly force is 1/<this value> "missile boats", weight guided munitions higher
    mtGuidedAmmoFriendlyMissileBoatFractionDivisor: 3.0
    # If off-board artillery units do not exceed this count, reduce weight of "utility" munitions (smoke, mines, flares)
    mtUtilityAmmoOffBoardUnitsThreshold: 2.0
    # If friendly forces: enemy forces does not exceed this fraction, reduce weight of "utility" munitions
    mtUtilityAmmoFriendlyVsEnemyFractionDivisor: 1.0
    # If enemy force is 1/<this value> "energy boats", increase heat-producing munition weight
    mtEnergyBoatEnemyFractionDivisor: 4.0
    # If enemy TSM-equipped units exceed this count, increase heat-seeking munition weight
    mtSeekingAmmoEnemyTSMExceedThreshold: 1.0
    # Weight cut-off beneath which to ignore munitions (final weights below this will never be equipped)
    mtMunitionWeightThreshold: 1.0
    # These factors determine how far up and down an "increase" or "decrease" step actually moves the weight
    # of a munition type.  The default values increase a weight by (2.0 x weight) + 1, and decrease by
    # (0.5 * weight), so no weight should end below 0 unless set there initially.
    increaseWeightFactor: 2.0
    increaseWeightIncrement: 1.0
    decreaseWeightFactor: 0.5
    decreaseWeightDecrement: 0.0
    # These factors determine how Pirates and Rebels are penalized for their low quality
    # Pirates and Rebels get ammo bins filled at random ratios -
    # Min(maxAllowed, Max(minAllowed, random/rangeDivisor + quality/qualityDivisor))
    # E.g. the defaults give a range of 20% to 100%, with Quality Rating 0 giving ~20%
    # and Rating 5 giving ~75% on average
    pirateMaxAllowedBinFillRatio: 1.0
    pirateMinAllowedBinFillRatio: 0.2
    pirateRandomRangeDivisor: 4.0
    pirateQualityDivisor: 8.0
